package berry;

import java.util.HashSet;
import javax.swing.JOptionPane;

public class registro_compra extends javax.swing.JFrame {
    private Controlador control = principal.control;
    compra c = new compra();
    public registro_compra() {
        initComponents();
        cargarClientesYProductos();
        
    }
    
         private cliente buscarClientePorCedula(String cedulaABuscar) {
    // control.getClientes() debería devolver tu ArrayList<Cliente>
    for (cliente cliente : control.getClientes()) { 
        // Se compara el número de documento (cedula) del cliente actual con el buscado
        if (cliente.getNumdocumento().equals(cedulaABuscar)) {
            // Si encuentra una coincidencia, retorna el objeto Cliente
            return cliente; 
        }
    }
    // Si el bucle termina y no se encontró el cliente, retorna null
    return null;}
        
    private void cargarClientesYProductos(){
        ClienteCombo.removeAllItems();
        ProductoCombo.removeAllItems();

        for (cliente c: control.getClientes()){  //Recorre el ArrayList
            ClienteCombo.addItem(String.valueOf("cc: "+c.getNumdocumento()));
        }
        
        for (producto p : control.getProductos()){
            String textoProducto = String.valueOf(p.getCodigo()) + " - " + (p.getMarca() + " - " + p.getReferencia());
            ProductoCombo.addItem(textoProducto);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        GuardarCompra = new javax.swing.JToggleButton();
        ProductoCombo = new javax.swing.JComboBox<>();
        ClienteLabel = new javax.swing.JLabel();
        ProductoLabel = new javax.swing.JLabel();
        ClienteCombo = new javax.swing.JComboBox<>();
        CantidadLabel = new javax.swing.JLabel();
        CantidadCampo = new javax.swing.JTextField();
        FechaLabel = new javax.swing.JLabel();
        FechaCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarritoArea = new javax.swing.JTextArea();
        TituloLista = new javax.swing.JLabel();
        TituloTotal = new javax.swing.JLabel();
        TituloDescuento = new javax.swing.JLabel();
        TituloPagar = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        DescuentoLabel = new javax.swing.JLabel();
        ValorPagarLabel = new javax.swing.JLabel();
        AñadirBoton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        SonicGif = new javax.swing.JLabel();
        FraseSonic = new javax.swing.JLabel();
        FraseSonic_2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        GuardarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GuardarCompra.setText("Guardar");
        GuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCompraActionPerformed(evt);
            }
        });

        ClienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClienteLabel.setText("Cliente:");

        ProductoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductoLabel.setText("Producto:");

        CantidadLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CantidadLabel.setText("Cantidad:");

        FechaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FechaLabel.setText("Fecha (año-mes-día):");

        CarritoArea.setColumns(20);
        CarritoArea.setRows(5);
        jScrollPane1.setViewportView(CarritoArea);

        TituloLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloLista.setText("Lista de Compra");

        TituloTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloTotal.setText("Total:");

        TituloDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloDescuento.setText("Descuento:");

        TituloPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloPagar.setText("Valor a Pagar:");

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalLabel.setText("0");

        DescuentoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DescuentoLabel.setText("0");

        ValorPagarLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ValorPagarLabel.setText("0");

        AñadirBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AñadirBoton.setText("Añadir Producto");
        AñadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirBotonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(51, 0, 51));
        TituloLabel.setText("Registro de la Compra");

        SonicGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berry/Materiales proyecto de Lógica/sonic.gif"))); // NOI18N
        SonicGif.setText("jLabel8");

        FraseSonic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FraseSonic.setText("Sonic dice:");

        FraseSonic_2.setBackground(new java.awt.Color(0, 0, 204));
        FraseSonic_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FraseSonic_2.setText("\"¡Corre, que se Agotan!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TituloTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(298, 298, 298)
                                                .addComponent(GuardarCompra))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(162, 162, 162)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FraseSonic, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TituloPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ValorPagarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TituloDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(DescuentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SonicGif, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FraseSonic_2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(FechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(CantidadCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(FechaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(115, 115, 115))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(AñadirBoton)))
                                        .addGap(353, 353, 353)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TituloLista)
                .addGap(339, 339, 339))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TituloLabel)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteLabel)
                    .addComponent(ClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoLabel))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadLabel)
                    .addComponent(CantidadCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñadirBoton))
                .addGap(23, 23, 23)
                .addComponent(TituloLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(FraseSonic_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloTotal)
                            .addComponent(TotalLabel)
                            .addComponent(GuardarCompra)
                            .addComponent(FraseSonic))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescuentoLabel)
                                    .addComponent(TituloDescuento))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TituloPagar)
                                    .addComponent(ValorPagarLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SonicGif)))
                        .addGap(77, 77, 77)))
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCompraActionPerformed
        String nombreCliente="";
        for (cliente c: control.getClientes()){  //Recorre el ArrayList
            if((ClienteCombo.getSelectedItem().toString().substring(4)).equals(c.getNumdocumento()))
                nombreCliente =c.getNombre() ;
        }
        String codigoProducto = ProductoCombo.getSelectedItem().toString().split(" - ")[0]; // solo el código
        String Fechacompra =FechaCampo.getText();
        int cantidad = Integer.parseInt(CantidadCampo.getText());

        cliente clienteSeleccionado = null;
        producto productoSeleccionado = null;
        
        for (cliente c: control.getClientes()){
            if (c.getNombre().equals(nombreCliente)){
                clienteSeleccionado = c;
                break;
            }
        }
        for (producto p : control.getProductos()) {
            if (p.getCodigo().equals(codigoProducto)) {
                productoSeleccionado = p;
                break;
            }
        }
      
        if (clienteSeleccionado != null && productoSeleccionado != null) {
            compra compraNueva = new compra(clienteSeleccionado, productoSeleccionado, cantidad, Fechacompra);
            control.agregarCompra(compraNueva);
            JOptionPane.showMessageDialog(this, "Compra registrada correctamente.\nFecha: " + Fechacompra + "\nTotal: $" + c.valorAPagar(clienteSeleccionado));
        }
        else { 
            JOptionPane.showMessageDialog(this, "Error: cliente o producto no encontrados.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Registrar la compra en el controlador principal
        
        
    
    }//GEN-LAST:event_GuardarCompraActionPerformed

    private void AñadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirBotonActionPerformed
        producto p=null;
        for (producto prod: control.getProductos()){
            if ((prod.getCodigo() + " - " + prod.getMarca() + " - " + prod.getReferencia()).equals(ProductoCombo.getSelectedItem().toString())){
                p=prod;
                c.agregarProductoACompra(p, Integer.parseInt(CantidadCampo.getText()));
            }
           
        }
        String cedulaSoloNumeros = ClienteCombo.getSelectedItem().toString().substring(4);
        CarritoArea.setText(c.mostrarProductosDeCompra());
        TotalLabel.setText(String.valueOf(c.calcularTotal()));
        c.setFecha(FechaCampo.getText());
        DescuentoLabel.setText(String.valueOf(c.aplicarDescuento(buscarClientePorCedula(cedulaSoloNumeros))));
        ValorPagarLabel.setText(String.valueOf(c.valorAPagar(buscarClientePorCedula(cedulaSoloNumeros))));
        if (p != null)
            JOptionPane.showMessageDialog(null,control.cantidadUnidades(p.getCodigo(), Integer.parseInt(CantidadCampo.getText())) );
    }//GEN-LAST:event_AñadirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirBoton;
    private javax.swing.JTextField CantidadCampo;
    private javax.swing.JLabel CantidadLabel;
    private javax.swing.JTextArea CarritoArea;
    private javax.swing.JComboBox<String> ClienteCombo;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JLabel DescuentoLabel;
    private javax.swing.JTextField FechaCampo;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JLabel FraseSonic;
    private javax.swing.JLabel FraseSonic_2;
    private javax.swing.JToggleButton GuardarCompra;
    private javax.swing.JComboBox<String> ProductoCombo;
    private javax.swing.JLabel ProductoLabel;
    private javax.swing.JLabel SonicGif;
    private javax.swing.JLabel TituloDescuento;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel TituloLista;
    private javax.swing.JLabel TituloPagar;
    private javax.swing.JLabel TituloTotal;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel ValorPagarLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

