/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package berry;


public class registro_producto extends javax.swing.JFrame {
    private Controlador control = principal.control;
   
    public registro_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CodigoCampo = new javax.swing.JTextField();
        MarcaCombo = new javax.swing.JComboBox<>();
        ReferenciaCampo = new javax.swing.JTextField();
        ColorCampo = new javax.swing.JTextField();
        ResolucionCombo = new javax.swing.JComboBox<>();
        PrecioCampo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ProductoCombo = new javax.swing.JComboBox<>();
        TelevisionLabel = new javax.swing.JLabel();
        ProyectorLabel = new javax.swing.JLabel();
        TipoUsoCampo = new javax.swing.JTextField();
        TipoUsoLabel = new javax.swing.JLabel();
        TipoTecnologiaLabel = new javax.swing.JLabel();
        TipoTecnologiaCombo = new javax.swing.JComboBox<>();
        TamañoPulgadaLabel = new javax.swing.JLabel();
        SizePantallaCombo = new javax.swing.JComboBox<>();
        TipoPantallaLabel = new javax.swing.JLabel();
        OSLabel = new javax.swing.JLabel();
        TipoPantallaCombo = new javax.swing.JComboBox<>();
        OSCombo = new javax.swing.JComboBox<>();
        UnidadCampo = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Codigo");

        jLabel2.setText("Referencia");

        jLabel3.setText("Marca");

        jLabel4.setText("Color");

        jLabel5.setText("Resolución");

        jLabel6.setText("Precio");

        jLabel7.setText("Unidades disponibles");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Registro del Producto");

        MarcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "LG", "Kalley" }));

        ResolucionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HD", "Full HD", "4K", "5k", "8k" }));

        jLabel10.setText("Producto");

        ProductoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Televisores", "Proyectores" }));
        ProductoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoComboActionPerformed(evt);
            }
        });

        TelevisionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TelevisionLabel.setText("Televisión");

        ProyectorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProyectorLabel.setText("Proyector");

        TipoUsoLabel.setText("Tipo Uso:");

        TipoTecnologiaLabel.setText("Tipo de Tecnología");

        TipoTecnologiaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LCD", "LED", "oLDP" }));

        TamañoPulgadaLabel.setText("Tamaño Pulgada");

        SizePantallaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 a 32", "40 a 49", "50 a 59", "60 a 75", "76 a más" }));

        TipoPantallaLabel.setText("Tipo Pantalla");

        OSLabel.setText("Sistema Operativo");

        TipoPantallaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LED", "mbanoCell", "OLED", "QLED", "Miniled", "QNED" }));

        OSCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android TV", "Google TV", "Tizen", "WebOS", "Roku TV" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResolucionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MarcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CodigoCampo)
                                .addComponent(ReferenciaCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(ColorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PrecioCampo)
                                .addComponent(UnidadCampo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoUsoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TipoUsoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoTecnologiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TipoTecnologiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TamañoPulgadaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipoPantallaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OSLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton1)))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(ProyectorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SizePantallaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelevisionLabel)
                    .addComponent(TipoPantallaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OSCombo, 0, 118, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodigoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ReferenciaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MarcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ColorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ResolucionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PrecioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UnidadCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelevisionLabel)
                    .addComponent(ProyectorLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoUsoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoUsoLabel)
                    .addComponent(TamañoPulgadaLabel)
                    .addComponent(SizePantallaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TipoTecnologiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoTecnologiaLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TipoPantallaLabel)
                                .addComponent(TipoPantallaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OSLabel)
                            .addComponent(OSCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo = CodigoCampo.getText();
        String marca = MarcaCombo.getSelectedItem().toString();
        String referencia = ReferenciaCampo.getText();
        String color = ColorCampo.getText();
        String resolucion = ResolucionCombo.getSelectedItem().toString();
        double precio = Double.parseDouble(PrecioCampo.getText());
        int unidad = Integer.parseInt(UnidadCampo.getText());
        if(ProductoCombo.getSelectedIndex() == 0){ 
            String size = SizePantallaCombo.getSelectedItem().toString();
            String tipoPantalla = TipoPantallaCombo.getSelectedItem().toString();
            String OS = OSCombo.getSelectedItem().toString();
            
            televisores tv = new televisores(codigo, marca, referencia ,color, resolucion, precio, unidad, size, tipoPantalla, OS);
            control.agregarProducto(tv);
            
            SizePantallaCombo.setSelectedIndex(0);
            TipoPantallaCombo.setSelectedIndex(0);
            OSCombo.setSelectedIndex(0);
            
        } else {
            String tipo = TipoUsoCampo.getText();
            String tecnologia = TipoTecnologiaCombo.getSelectedItem().toString();
            proyectores proyector = new proyectores(codigo, marca, referencia ,color, resolucion, precio, unidad, tipo, tecnologia);
            control.agregarProducto(proyector);
            
            TipoUsoCampo.setText(null);
            
            TipoTecnologiaCombo.setSelectedIndex(0);
            
            
        }
        
        MarcaCombo.setSelectedIndex(0);
        ProductoCombo.setSelectedIndex(0);
        ResolucionCombo.setSelectedIndex(0);
        CodigoCampo.setText(null);
        ReferenciaCampo.setText(null);
        ColorCampo.setText(null);
        PrecioCampo.setText(null);
        UnidadCampo.setText(null);
        javax.swing.JOptionPane.showMessageDialog(this, "Producto registrado correctamente");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProductoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoComboActionPerformed
        if (ProductoCombo.getSelectedIndex() ==0){
            //Labels visibles
            
            TelevisionLabel.setVisible(true);
            TamañoPulgadaLabel.setVisible(true);
            TipoPantallaLabel.setVisible(true);
            OSLabel.setVisible(true);
            
            // ComboBox visibles
            
            SizePantallaCombo.setVisible(true);
            TipoPantallaCombo.setVisible(true);
            OSCombo.setVisible(true);
            
            // Labels invisibles
            ProyectorLabel.setVisible(false);
            TipoUsoLabel.setVisible(false);
            TipoTecnologiaLabel.setVisible(false);
            
            // Combo Box
            
            TipoTecnologiaCombo.setVisible(false);
            
            //Campo
            
            TipoUsoCampo.setVisible(false);
        } else {
            
            TelevisionLabel.setVisible(false);
            TamañoPulgadaLabel.setVisible(false);
            TipoPantallaLabel.setVisible(false);
            OSLabel.setVisible(false);
            
           
            
            SizePantallaCombo.setVisible(false);
            TipoPantallaCombo.setVisible(false);
            OSCombo.setVisible(false);
            
           
            ProyectorLabel.setVisible(true);
            TipoUsoLabel.setVisible(true);
            TipoTecnologiaLabel.setVisible(true);
            
         
            
            TipoTecnologiaCombo.setVisible(true);
            
            
            
            TipoUsoCampo.setVisible(true);
        }
           
    }//GEN-LAST:event_ProductoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoCampo;
    private javax.swing.JTextField ColorCampo;
    private javax.swing.JComboBox<String> MarcaCombo;
    private javax.swing.JComboBox<String> OSCombo;
    private javax.swing.JLabel OSLabel;
    private javax.swing.JTextField PrecioCampo;
    private javax.swing.JComboBox<String> ProductoCombo;
    private javax.swing.JLabel ProyectorLabel;
    private javax.swing.JTextField ReferenciaCampo;
    private javax.swing.JComboBox<String> ResolucionCombo;
    private javax.swing.JComboBox<String> SizePantallaCombo;
    private javax.swing.JLabel TamañoPulgadaLabel;
    private javax.swing.JLabel TelevisionLabel;
    private javax.swing.JComboBox<String> TipoPantallaCombo;
    private javax.swing.JLabel TipoPantallaLabel;
    private javax.swing.JComboBox<String> TipoTecnologiaCombo;
    private javax.swing.JLabel TipoTecnologiaLabel;
    private javax.swing.JTextField TipoUsoCampo;
    private javax.swing.JLabel TipoUsoLabel;
    private javax.swing.JTextField UnidadCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
