/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package berry;


public class registro_producto extends javax.swing.JFrame {
    private Controlador control = principal.control;
   
    public registro_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CodigoLabel = new javax.swing.JLabel();
        ReferenciaLabel = new javax.swing.JLabel();
        MarcaLabel = new javax.swing.JLabel();
        ColorLabel = new javax.swing.JLabel();
        ResolucionLabel = new javax.swing.JLabel();
        PrecioLabel = new javax.swing.JLabel();
        UnidadDisLabel = new javax.swing.JLabel();
        GuardarBoton = new javax.swing.JButton();
        TituloProducto = new javax.swing.JLabel();
        CodigoCampo = new javax.swing.JTextField();
        MarcaCombo = new javax.swing.JComboBox<>();
        ReferenciaCampo = new javax.swing.JTextField();
        ColorCampo = new javax.swing.JTextField();
        ResolucionCombo = new javax.swing.JComboBox<>();
        PrecioCampo = new javax.swing.JTextField();
        ProductoLabel = new javax.swing.JLabel();
        ProductoCombo = new javax.swing.JComboBox<>();
        TelevisionLabel = new javax.swing.JLabel();
        ProyectorLabel = new javax.swing.JLabel();
        TipoUsoCampo = new javax.swing.JTextField();
        TipoUsoLabel = new javax.swing.JLabel();
        TipoTecnologiaLabel = new javax.swing.JLabel();
        TipoTecnologiaCombo = new javax.swing.JComboBox<>();
        TamañoPulgadaLabel = new javax.swing.JLabel();
        SizePantallaCombo = new javax.swing.JComboBox<>();
        TipoPantallaLabel = new javax.swing.JLabel();
        OSLabel = new javax.swing.JLabel();
        TipoPantallaCombo = new javax.swing.JComboBox<>();
        OSCombo = new javax.swing.JComboBox<>();
        UnidadCampo = new javax.swing.JTextField();
        Monitor = new javax.swing.JLabel();
        FraseSonic = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        CodigoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CodigoLabel.setText("Codigo:");

        ReferenciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReferenciaLabel.setText("Referencia:");

        MarcaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MarcaLabel.setText("Marca:");

        ColorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ColorLabel.setText("Color:");

        ResolucionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResolucionLabel.setText("Resolución:");

        PrecioLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PrecioLabel.setText("Precio:");

        UnidadDisLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UnidadDisLabel.setText("Unidades disponibles:");

        GuardarBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuardarBoton.setText("Guardar");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });

        TituloProducto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TituloProducto.setText("Registro del Producto");

        MarcaCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MarcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "LG", "Kalley" }));

        ResolucionCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResolucionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HD", "Full HD", "4K", "5k", "8k" }));

        ProductoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductoLabel.setText("Producto:");

        ProductoCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Televisores", "Proyectores" }));
        ProductoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoComboActionPerformed(evt);
            }
        });

        TelevisionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TelevisionLabel.setText("Televisión");

        ProyectorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProyectorLabel.setText("Proyector");

        TipoUsoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TipoUsoLabel.setText("Tipo Uso:");

        TipoTecnologiaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TipoTecnologiaLabel.setText("Tipo de Tecnología:");

        TipoTecnologiaCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TipoTecnologiaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LCD", "LED", "oLDP" }));

        TamañoPulgadaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TamañoPulgadaLabel.setText("Tamaño Pulgada:");

        SizePantallaCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SizePantallaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 a 32", "40 a 49", "50 a 59", "60 a 75", "76 a más" }));

        TipoPantallaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TipoPantallaLabel.setText("Tipo Pantalla:");

        OSLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OSLabel.setText("Sistema Operativo:");

        TipoPantallaCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TipoPantallaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LED", "mbanoCell", "OLED", "QLED", "Miniled", "QNED" }));

        OSCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OSCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android TV", "Google TV", "Tizen", "WebOS", "Roku TV" }));

        Monitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berry/Materiales proyecto de Lógica/monitores.gif"))); // NOI18N

        FraseSonic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FraseSonic.setText("¡Disfruta de tu compra!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 438, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FraseSonic, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProductoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(ProyectorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SizePantallaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelevisionLabel)
                    .addComponent(TipoPantallaCombo, 0, 118, Short.MAX_VALUE))
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoUsoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TipoUsoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoTecnologiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TipoTecnologiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TamañoPulgadaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(TipoPantallaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(GuardarBoton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OSCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CodigoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResolucionLabel)
                        .addComponent(PrecioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReferenciaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(MarcaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UnidadDisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TituloProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResolucionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MarcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CodigoCampo)
                                .addComponent(ReferenciaCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(ColorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PrecioCampo)
                                .addComponent(UnidadCampo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Monitor)
                        .addGap(101, 101, 101))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TituloProducto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReferenciaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReferenciaCampo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(FraseSonic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarcaLabel)
                            .addComponent(MarcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorLabel)
                            .addComponent(ColorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResolucionLabel)
                            .addComponent(ResolucionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Monitor))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioLabel)
                    .addComponent(PrecioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductoLabel)
                    .addComponent(ProductoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadDisLabel)
                    .addComponent(UnidadCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelevisionLabel)
                    .addComponent(ProyectorLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoUsoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoUsoLabel)
                    .addComponent(TamañoPulgadaLabel)
                    .addComponent(SizePantallaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoTecnologiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoTecnologiaLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TipoPantallaLabel)
                                .addComponent(TipoPantallaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OSLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OSCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(GuardarBoton)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        String codigo = CodigoCampo.getText();
        String marca = MarcaCombo.getSelectedItem().toString();
        String referencia = ReferenciaCampo.getText();
        String color = ColorCampo.getText();
        String resolucion = ResolucionCombo.getSelectedItem().toString();
        double precio = Double.parseDouble(PrecioCampo.getText());
        int unidad = Integer.parseInt(UnidadCampo.getText());
        if(ProductoCombo.getSelectedIndex() == 0){ 
            String size = SizePantallaCombo.getSelectedItem().toString();
            String tipoPantalla = TipoPantallaCombo.getSelectedItem().toString();
            String OS = OSCombo.getSelectedItem().toString();
            
            televisores tv = new televisores(codigo, marca, referencia ,color, resolucion, precio, unidad, size, tipoPantalla, OS);
            control.agregarProducto(tv);
            
            SizePantallaCombo.setSelectedIndex(0);
            TipoPantallaCombo.setSelectedIndex(0);
            OSCombo.setSelectedIndex(0);
            
        } else {
            String tipo = TipoUsoCampo.getText();
            String tecnologia = TipoTecnologiaCombo.getSelectedItem().toString();
            proyectores proyector = new proyectores(codigo, marca, referencia ,color, resolucion, precio, unidad, tipo, tecnologia);
            control.agregarProducto(proyector);
            
            TipoUsoCampo.setText(null);
            
            TipoTecnologiaCombo.setSelectedIndex(0);
            
            
        }
        
        MarcaCombo.setSelectedIndex(0);
        ProductoCombo.setSelectedIndex(0);
        ResolucionCombo.setSelectedIndex(0);
        CodigoCampo.setText(null);
        ReferenciaCampo.setText(null);
        ColorCampo.setText(null);
        PrecioCampo.setText(null);
        UnidadCampo.setText(null);
        javax.swing.JOptionPane.showMessageDialog(this, "Producto registrado correctamente");

    }//GEN-LAST:event_GuardarBotonActionPerformed

    private void ProductoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoComboActionPerformed
        if (ProductoCombo.getSelectedIndex() ==0){
            //Labels visibles
            
            TelevisionLabel.setVisible(true);
            TamañoPulgadaLabel.setVisible(true);
            TipoPantallaLabel.setVisible(true);
            OSLabel.setVisible(true);
            
            // ComboBox visibles
            
            SizePantallaCombo.setVisible(true);
            TipoPantallaCombo.setVisible(true);
            OSCombo.setVisible(true);
            
            // Labels invisibles
            ProyectorLabel.setVisible(false);
            TipoUsoLabel.setVisible(false);
            TipoTecnologiaLabel.setVisible(false);
            
            // Combo Box
            
            TipoTecnologiaCombo.setVisible(false);
            
            //Campo
            
            TipoUsoCampo.setVisible(false);
        } else {
            
            TelevisionLabel.setVisible(false);
            TamañoPulgadaLabel.setVisible(false);
            TipoPantallaLabel.setVisible(false);
            OSLabel.setVisible(false);
            
           
            
            SizePantallaCombo.setVisible(false);
            TipoPantallaCombo.setVisible(false);
            OSCombo.setVisible(false);
            
           
            ProyectorLabel.setVisible(true);
            TipoUsoLabel.setVisible(true);
            TipoTecnologiaLabel.setVisible(true);
            
         
            
            TipoTecnologiaCombo.setVisible(true);
            
            
            
            TipoUsoCampo.setVisible(true);
        }
           
    }//GEN-LAST:event_ProductoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoCampo;
    private javax.swing.JLabel CodigoLabel;
    private javax.swing.JTextField ColorCampo;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JLabel FraseSonic;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JComboBox<String> MarcaCombo;
    private javax.swing.JLabel MarcaLabel;
    private javax.swing.JLabel Monitor;
    private javax.swing.JComboBox<String> OSCombo;
    private javax.swing.JLabel OSLabel;
    private javax.swing.JTextField PrecioCampo;
    private javax.swing.JLabel PrecioLabel;
    private javax.swing.JComboBox<String> ProductoCombo;
    private javax.swing.JLabel ProductoLabel;
    private javax.swing.JLabel ProyectorLabel;
    private javax.swing.JTextField ReferenciaCampo;
    private javax.swing.JLabel ReferenciaLabel;
    private javax.swing.JComboBox<String> ResolucionCombo;
    private javax.swing.JLabel ResolucionLabel;
    private javax.swing.JComboBox<String> SizePantallaCombo;
    private javax.swing.JLabel TamañoPulgadaLabel;
    private javax.swing.JLabel TelevisionLabel;
    private javax.swing.JComboBox<String> TipoPantallaCombo;
    private javax.swing.JLabel TipoPantallaLabel;
    private javax.swing.JComboBox<String> TipoTecnologiaCombo;
    private javax.swing.JLabel TipoTecnologiaLabel;
    private javax.swing.JTextField TipoUsoCampo;
    private javax.swing.JLabel TipoUsoLabel;
    private javax.swing.JLabel TituloProducto;
    private javax.swing.JTextField UnidadCampo;
    private javax.swing.JLabel UnidadDisLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
